export type SeoGuide = { slug: string; title: string; description: string; heading: string; sections: { heading: string; text: string }[]; links: { label: string; href: string }[] };
export const seoGuides: SeoGuide[] = [
  { slug: "luparka-przekladniowa-czy-hydrauliczna", title: "Łuparka przekładniowa czy hydrauliczna?", description: "Porównanie mechanizmu, szybkości pracy, obsługi i zastosowań.", heading: "Łuparka przekładniowa czy hydrauliczna — różnice", sections: [
    { heading: "Dwa sposoby napędu", text: "Łuparka hydrauliczna wykorzystuje pompę, olej, zawór i siłownik. Łuparka przekładniowa przekazuje moment przez silnik, pasy i reduktor, dlatego nie ma typowego układu hydraulicznego, przewodów ani siłownika." },
    { heading: "Tempo i obsługa", text: "Mechanizm przekładniowy zapewnia regularny cykl, przydatny przy seryjnym przygotowaniu drewna. Wymaga kontroli oleju w przekładni, pasów, łożysk i osłon. Hydraulika pracuje inaczej i wymaga obsługi oleju, przewodów oraz uszczelnień." },
    { heading: "Wybór do pracy", text: "Porównaj średnicę i długość polan, rodzaj drewna, dostępne zasilanie, organizację stanowiska i serwis. Każdą konstrukcję należy oceniać według jej instrukcji, zastosowanych osłon, sterowania i procedur bezpieczeństwa." }
  ], links: [{ label: "Łuparki POLMECH.TECH", href: "/kategoria/luparka-przekladniowa" }, { label: "Kontakt", href: "/o-nas" }] },
  { slug: "luparka-230v-czy-400v", title: "Łuparka 400 V do drewna — dlaczego 3 kW?", description: "Dlaczego aktualna łuparka POLMECH.TECH wykorzystuje trójfazowy silnik 3 kW / 400 V.", heading: "Łuparka do drewna 400 V / 3 kW — wybór POLMECH.TECH", sections: [
    { heading: "Dlaczego 400 V", text: "Aktualna kompletna łuparka POLMECH.TECH wykorzystuje silnik trójfazowy PROMOTOR 3 kW / 400 V. Taki układ został przyjęty po testach konstrukcji pod obciążeniem." },
    { heading: "Do regularnej pracy", text: "Napęd 400 V współpracuje z reduktorem i dwoma przeciwległymi klinami. Konstrukcja jest przeznaczona do powtarzalnego łupania drewna opałowego, w tym polan sękatych i nieregularnych." },
    { heading: "Nie tylko napięcie", text: "O wydajności decydują także moc, przełożenie, geometria klina, sposób podawania polana i sprawność całego napędu. Przed zakupem porównaj warunki gwarancji, serwis i dostępność części." }
  ], links: [{ label: "Aktualne modele", href: "/kategoria/luparka-przekladniowa" }, { label: "Dostawa", href: "/dostawa" }] },
  { slug: "jak-ustawic-polano-w-luparce", title: "Jak ustawić polano w łuparce?", description: "Pozycja polana, praca z sękami i ograniczanie zakleszczeń.", heading: "Jak prawidłowo ustawić polano w łuparce przekładniowej", sections: [
    { heading: "Stabilne podparcie", text: "Polano ustaw stabilnie i zgodnie z zakresem wymiarów maszyny. Nie podtrzymuj go ręką w strefie klina i nie wkładaj dłoni między drewno a elementy konstrukcji. Stanowisko powinno być równe i wolne od odpadów." },
    { heading: "Wejście klina", text: "Przy nieregularnym drewnie korzystne jest skierowanie klina około 2–3 cm od krawędzi polana zamiast dokładnie w środek największego sęka. Zmniejsza to ryzyko zakleszczenia i pozwala stopniowo rozdzielać włókna." },
    { heading: "Gdy drewno się zatrzyma", text: "Nie poprawiaj polana przy pracującym napędzie. Zatrzymaj maszynę i użyj procedury rewersu opisanej w instrukcji. Nie zwiększaj siły przez obchodzenie zabezpieczeń ani modyfikowanie sterowania." }
  ], links: [{ label: "Łuparki przekładniowe", href: "/kategoria/luparka-przekladniowa" }, { label: "Bezpieczeństwo", href: "/poradnik/bezpieczenstwo-luparki-do-drewna" }] },
  { slug: "przekladnia-jzq250-do-luparki", title: "Przekładnia JZQ250 do łuparki", description: "Przełożenie, smarowanie, pasy i kontrola przekładni JZQ250.", heading: "Przekładnia JZQ250 w łuparce — dobór i eksploatacja", sections: [
    { heading: "Rola przełożenia", text: "Reduktor obniża prędkość obrotową i zwiększa moment dostępny na mechanizmie roboczym. Przełożenie trzeba oceniać razem z prędkością silnika oraz średnicami kół pasowych, ponieważ wszystkie te elementy wyznaczają cykl pracy." },
    { heading: "Olej i ustawienie", text: "Przed pierwszym uruchomieniem sprawdź poziom i rodzaj oleju zgodnie z instrukcją. Przekładnia powinna pracować w przewidzianej pozycji, a odpowietrzenie nie może być zablokowane. Wyciek lub nadmierna temperatura wymaga zatrzymania urządzenia." },
    { heading: "Pasy i łożyska", text: "Koła pasowe muszą znajdować się w jednej płaszczyźnie, a napięcie pasów nie może przeciążać łożysk. Regularnie kontroluj mocowanie, hałas, luzy i temperaturę obudowy." }
  ], links: [{ label: "Przekładnie i moduły", href: "/kategoria/luparka-przekladniowa" }, { label: "Serwis", href: "/o-nas" }] },
  { slug: "bezpieczenstwo-luparki-do-drewna", title: "Bezpieczeństwo łuparki do drewna", description: "Stanowisko, osłony, sterowanie i procedura awaryjna.", heading: "Bezpieczna praca łuparką przekładniową do drewna", sections: [
    { heading: "Przed uruchomieniem", text: "Przeczytaj instrukcję, skontroluj osłony, przewody, wyłącznik awaryjny, kierunek obrotów i stabilność maszyny. Usuń ze stanowiska osoby postronne oraz przedmioty, o które operator może się potknąć." },
    { heading: "Podczas pracy", text: "Używaj wyłącznie przewidzianego sterowania i trzymaj ręce poza strefą klina. Nie próbuj przytrzymywać pękającego drewna. Stosuj ochronę oczu, słuchu, obuwie ochronne i odzież bez luźnych elementów." },
    { heading: "Zakleszczenie i serwis", text: "Przed usuwaniem drewna zatrzymaj napęd i odłącz zasilanie. Rewers stosuj zgodnie z instrukcją; nie omijaj blokad. Naprawy instalacji elektrycznej oraz napędu powinny wykonywać osoby z odpowiednimi kwalifikacjami." }
  ], links: [{ label: "Modele POLMECH.TECH", href: "/kategoria/luparka-przekladniowa" }, { label: "Gwarancja", href: "/zwroty-i-reklamacje" }] },
  { slug: "luparka-do-drewna-sekatego", title: "Jaka łuparka do drewna sękatego?", description: "Na co zwrócić uwagę przy łupaniu sęków, rozwidleń i nieregularnych polan.", heading: "Łuparka do drewna sękatego i rozwidleń — co ma znaczenie", sections: [
    { heading: "Trudne drewno to nie tylko średnica", text: "Sęki, rozwidlenia i skręcone włókna mogą być większym wyzwaniem niż sama średnica polana. Warto oceniać mechanizm, geometrię klina, sposób podawania i zachowanie maszyny przy zakleszczeniu." },
    { heading: "Konstrukcja POLMECH.TECH", text: "Łuparka POLMECH.TECH pracuje mechanicznie przez reduktor i dwa przeciwległe kliny. Aktualny model wykorzystuje silnik PROMOTOR 3 kW / 400 V i jest przeznaczony do polan do około 40 cm średnicy oraz 50 cm długości." },
    { heading: "Sęki i rozwidlenia w praktyce", text: "Przy trudnym polanie znaczenie ma miejsce wejścia klina. Materiał należy podawać zgodnie z instrukcją i z użyciem przewidzianych kleszczy, bez wkładania dłoni w strefę roboczą." }
  ], links: [{ label: "Łuparka POLMECH.TECH 400 V", href: "/kategoria/luparka-przekladniowa" }, { label: "Jak ustawić polano", href: "/poradnik/jak-ustawic-polano-w-luparce" }] },
  { slug: "luparka-do-tui-i-rozwidlen", title: "Łuparka do tui i rozwidleń", description: "Jak podejść do trudnego, włóknistego i rozwidlonego drewna opałowego.", heading: "Łupanie tui, rozwidleń i nieregularnego drewna", sections: [
    { heading: "Dlaczego takie drewno jest trudne", text: "Tuja, rozwidlenia i mocno nieregularne kawałki nie rozdzielają się tak przewidywalnie jak proste polana. Układ włókien i sęków zwiększa znaczenie kontrolowanego, powtarzalnego podawania materiału." },
    { heading: "Dwa przeciwległe kliny", text: "W konstrukcji POLMECH.TECH zastosowano dwa przeciwległe kliny na wolnoobrotowym mechanizmie przekładniowym. Przy około 9,5 obrotu mechanizmu na minutę daje to około 19 kontaktów klina z drewnem na minutę." },
    { heading: "Bezpieczne podawanie", text: "POLMECH.TECH przewiduje podawanie polan specjalnymi kleszczami. Przy zakleszczeniu należy zatrzymać maszynę i zastosować procedurę ograniczonego rewersu zgodnie z instrukcją." }
  ], links: [{ label: "Zobacz łuparki przekładniowe", href: "/kategoria/luparka-przekladniowa" }, { label: "Bezpieczeństwo pracy", href: "/poradnik/bezpieczenstwo-luparki-do-drewna" }] },
  { slug: "jak-wybrac-luparke-mechaniczna", title: "Jak wybrać łuparkę mechaniczną do drewna?", description: "Mechanizm, zasilanie, wymiary polan, tempo pracy, bezpieczeństwo i serwis.", heading: "Jak wybrać łuparkę mechaniczną — praktyczne kryteria", sections: [
    { heading: "Nie tylko deklarowana siła", text: "Przy porównywaniu łuparek warto sprawdzić rodzaj napędu, przełożenie, geometrię klina, dopuszczalną średnicę i długość polana, tempo cyklu oraz sposób rozwiązania zakleszczeń." },
    { heading: "Zasilanie i charakter pracy", text: "Aktualny POLMECH.TECH 3KW/400/S wykorzystuje trójfazowy silnik 3 kW / 400 V. Maszyna jest przeznaczona dla użytkowników mających dostęp do zasilania 400 V i przygotowujących drewno seryjnie." },
    { heading: "Serwis i części", text: "Przy maszynie mechanicznej ważna jest dostępność elementów eksploatacyjnych i wsparcia po zakupie. POLMECH.TECH zapewnia gwarancję, serwis i dostęp do części w Polsce." }
  ], links: [{ label: "Aktualne łuparki POLMECH.TECH", href: "/kategoria/luparka-przekladniowa" }, { label: "Przekładniowa czy hydrauliczna", href: "/poradnik/luparka-przekladniowa-czy-hydrauliczna" }] }
];
export const getSeoGuide = (slug: string) => seoGuides.find((guide) => guide.slug === slug);
